[package]
name = "spirv-builder"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
memchr = "2.3"
raw-string = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# TODO: Update before merge.
cargo-sysroot = { git = "https://github.com/XAMPPRocky/cargo-sysroot", branch = "main" }
git2 = "0.13.12"
eyre = "0.6.2"
remove_dir_all = "0.6.1"

[dev-dependencies]
lazy_static = "1.4"
pretty_assertions = "0.6"
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "01ca0d2e5b667a0e4ff1bc1804511e38f9a08759" }
